from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.index,
        name='index'),
    path(
        'login/',
        views.login_view,
        name='login'),
    path(
        'about/',
        views.about,
        name='about'),
    path(
        'register/',
        views.register,
        name='register'),
    path(
        'logout/',
        views.logout,
        name='logout'),
    path(
        'products/',
        views.products,
        name='products'),
    path(
        'product/<int:product_id>/',
        views.product_detail,
        name='product_detail'),
    path(
        'checkout/',
        views.checkout,
        name='checkout'),
    path(
        'payment/',
        views.payment,
        name='payment'),
    path(
        'charge/',
        views.charge,
        name='charge'),
    path(
        'add_to_basket/<int:product_id>/',
        views.add_to_basket,
        name='add_to_basket'),
    path(
        'remove_from_basket/<int:item_id>/',
        views.remove_from_basket,
        name='remove_from_basket'),
    path(
        'dashboard/',
        views.dashboard,
        name='dashboard'),
    path(
        'profile/',
        views.profile,
        name='profile'),
]
