# Generated by Django 4.2.7 on 2024-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_auto_20240325_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="second_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
