# Generated by Django 4.2.7 on 2024-04-03 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0010_purchase"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Purchase",
            new_name="catalog_purchase",
        ),
    ]
