# Generated by Django 4.2.7 on 2024-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_product_image5_product_image6"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="book_type",
            field=models.CharField(
                choices=[("PB", "Paperback"), ("HB", "Hardback")],
                default="PB",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_hardback",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="product",
            name="price_paperback",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
