# Generated by Django 4.2.7 on 2024-04-14 19:07

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_orderitem_order_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="item",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=catalog.models.get_default_product,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
