# Generated by Django 3.2.25 on 2024-04-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_basketitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_hardback',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_paperback',
        ),
    ]
