# Generated by Django 3.2.25 on 2024-04-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20240425_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
