# Generated by Django 4.2.7 on 2024-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email",
            field=models.EmailField(default="default@email.com", max_length=254),
        ),
    ]
