# Generated by Django 4.2.7 on 2024-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_message_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
    ]
