# Generated by Django 3.2.23 on 2024-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='title',
            field=models.CharField(default='deafult@example.com', max_length=200),
            preserve_default=False,
        ),
    ]
